# Generated by Django 5.0.1 on 2024-01-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoption',
            new_name='Adoption1',
        ),
    ]
