# Generated by Django 5.0.1 on 2024-01-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_adoption1_adoption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adoption',
            new_name='Cat_Adoption',
        ),
    ]
