# Generated by Django 5.0.1 on 2024-01-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_comment_delete_cat_adoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='description',
        ),
    ]
